### PR TITLE
adding nrt workflows

### PR DESCRIPTION
**Pull request by BuddyVolly**
This PR adds descriptions to the workflow section regarding the new NRT recipes and their usage

### CODE REVIEW

**Comment by dfguerrerom** [comment]
@alexryangregor would you mind reviewing this new page?

**Comment by 12rambau** [comment]
@dfguerrerom small gift from switzerland, all tests are green now ;-)

**Comment by dfguerrerom** [comment]
@alexryangregor there's not a specific urgency with this review, but if you think this can take a "long" time, we can bypass your review and you can review it later. No rush with this.

**Comment by alexryangregor** [comment]
> @alexryangregor there's not a specific urgency with this review, but if you think this can take a "long" time, we can bypass your review and you can do it later. No rush with this.

No problem, @dfguerrerom. I'll take care of it asap.

Can you please check the following screenshots to ensure I'm reviewing the correct file?

image

image

Many thanks!

**Review by alexryangregor — APPROVED** [review]
I reviewed and updated the entire page, as I had not yet edited the text. 

Marking it as reviewed and approved.

**Review by dfguerrerom — APPROVED** [review]

**Comment by alexryangregor** [comment]
@dfguerrerom I would like to review this page again and provide some minor edits; however, the edit function isn't available (see screenshot below). Can you please make it available?

image

**Comment by dfguerrerom** [comment]
I assume you're on the default branch, change it to the "copy_writing" one, it should be activated (check the selectable list that says `main` )

image

**Comment by alexryangregor** [comment]
@dfguerrerom It doesn't appear to be active.

image

**Comment by dfguerrerom** [comment]
That is because you are trying to edit the fork in Andrea's repository.
Note that **this** branch is already merged in `main`, (and, as `copy_writing` branch was created from that `main`), you can edit the `bayts.rst` file directly in the `copy_writing` branch (go here https://github.com/openforis/sepal-doc/blob/copy_writing/docs/source/workflows/bayts.rst).

**Comment by alexryangregor** [comment]
Thank you @dfguerrerom. Will do.

**Pull request merged**
