### PR TITLE
Copy editing

### PR DESCRIPTION
**Pull request by alexryangregor**
Note: Copy editing has not yet been completed. Since there is so much text on this page, I will be proposing changes to save my progress. Once I have finished, I will let you know.

### CODE REVIEW

**Comment by 12rambau** [comment]
I've converted your PR to draft so that everyone can see it's a WIP

**Comment by alexryangregor** [comment]
> I've converted your PR to draft so that everyone can see it's a WIP

Thanks, Pierrick!

**Comment by alexryangregor** [comment]
> I've converted your PR to draft so that everyone can see it's a WIP

@12rambau : Pierrick, I have a quick question for you. Once I finish this page, I'm going to apply the style from the style guide to the "Getting started" section.  Can I apply the style to the already copy-edited text in the "Getting started" section? If so, should I make another pull request or edit the pull requests that I've already made? Thanks!

**Comment by 12rambau** [comment]
As you may have seen nearly all your existing PR have been validated by Erik so I merged them into the main branch. 
You can start back from the "edit button" as the previous modification are already included in the latest build

**Comment by alexryangregor** [comment]
> 

Excellent. Thank you!

**Comment by alexryangregor** [comment]
@12rambau I hope all's well with you. I accidentally just marked my most recent PR "ready for review"; however, it is not yet ready. I will let you know once it is.

I have been very busy with other projects and will move forward with the doc page as soon as I can.

Thanks!

**Comment by dfguerrerom** [comment]
> @12rambau I hope all's well with you. I accidentally just marked my most recent PR "ready for review"; however, it is not yet ready. I will let you know once it is.
> 
> I have been very busy with other projects and will move forward with the doc page as soon as I can.
> 
> Thanks!

@alexryangregor there is a link in the right panel in this form, you can "convert to draft" this PR.

**Comment by alexryangregor** [comment]
Copy editing has been completed.

**Review by 12rambau — APPROVED** [review]

**Pull request merged**
