### PR TITLE
docs: document new auth process with GCP

### PR DESCRIPTION
**Pull request by dfguerrerom**
@alexryangregor, please see the changes here: https://github.com/openforis/sepal-doc/pull/565/files#diff-4f38c57dd95fc0c4720d6fcaf10f23f80d24fed3d4a6177b80b009da2d9e22cf.

and the live version of the page changed: 
https://sepal-doc--565.org.readthedocs.build/en/565/setup/gee.html

### CODE REVIEW

**Review by alexryangregor — CHANGES_REQUESTED** [review]
@dfguerrerom I'm attempting to edit the new text in your commits, but am unable (see attached screenshot). Is there another way to edit a commit during my review, or can you simply provide me with editing access?

Screenshot 2024-01-02 at 11 18 11

**Comment by 12rambau** [comment]
@alexryangregor I gave you write access to the repository you should now be able to modify the files in the `doc_new_auth` branch. 
I let @dfguerrerom chat with you if you need any further guidances.

**Review by alexryangregor — APPROVED** [review]
After editing some of the text in the commits, the page is now ready to go live.

**Comment by alexryangregor** [comment]
@12rambau many thanks for your help. Edits were made, my review is complete, and the page is ready to go live.

**Pull request merged**
